- name: Install packages
  ansible.builtin.package:
    name: '{{ packages }}'
    update_cache: true
    state: present
  vars:
    packages:
      - net-tools
      - openvpn
      - build-essential
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - dnsutils
      - traceroute
      - tcpdump
      - jq
  register: result
  retries: 3
  delay: '{{ proxmox_timeouts.creation }}'
  until: result is not failed

- name: Join Vpn
  when: vpn_name is defined
  block:
    - name: Init vpn service
      ansible.builtin.template:
        src: lab_vpn.service.j2
        dest: /etc/systemd/system/lab_vpn.service
        owner: root
        group: root
        mode: '0644'
      register: result

    - name: Create directory for openvpn
      ansible.builtin.file:
        path: /opt/openvpn
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy Vpn Keys
      ansible.builtin.copy:
        src: '{{ vpn.key_dir }}/{{ vpn_name }}.ovpn'
        dest: /opt/openvpn/client.ovpn
        owner: root
        group: root
        mode: '0644'
      notify: Restart vpn service
