- name: Install packages
  ansible.builtin.package:
    name:
      - net-tools
  register: result
  retries: 3
  delay: '{{ proxmox_timeouts.creation }}'
  until: result is not failed

- name: Init vpn service
  ansible.builtin.template:
    src: lab_vpn.service.j2
    dest: /etc/systemd/system/lab_vpn.service
    owner: root
    group: root
    mode: '0644'
  register: result

- name: Resize disk to use all available splace
  ansible.builtin.shell:
    cmd: |
      growpart /dev/sda 3
      resize2fs /dev/sda3
  register: result
  changed_when: result.stdout != ""
