---
ansible_maximal_version: 2.16.8
ansible_minimal_version: 2.14.0
mode: debug
cluster_network:
  cidr: 24
  gateway: 192.168.1.1
proxmox_api:
  host: 192.168.1.xx
  user: root@pam
  token_id: cluster_admin
  token_secret: 1234abc
proxmox_timeouts:
  api: 120
  common: 30
  creation: 15
  startup: 300
  shutdown: 600
  disk_change: 720
agent:
  user: root
  pass: 123
  sskkeys: abc
virtual_machines:
  # - vmid: 101
  #   name: loadbalancer
  #   clone: ubuntu-22.04-server-amd64
  #   node: promox
  #   cores: 2
  #   memory: 2048
  #   autostart: true
  #   ip: 192.168.1.50
  #   disks:
  #     - size: +5G
  #       disk: scsi0
  #       state: resized
  #     - size: 10
  #       disk: scsi1
  #       state: present
  #       storage: data
  #       format: raw
  # - vmid: 102
  #   name: seed_server
  #   clone: ubuntu-22.04-server-amd64
  #   node: promox
  #   cores: 2
  #   memory: 2048
  #   autostart: true
  # - vmid: 103
  #   name: seed_server
  #   clone: ubuntu-22.04-server-amd64
  #   node: promox1
  #   cores: 2
  #   memory: 2048
  #   autostart: true
