---
- name: Create VM from template
  block:
    - name: Debug vm
      ansible.builtin.debug:
        msg: '{{ vm }}'
      when: mode is defined and mode == "debug"

    - name: Create VM
      community.general.proxmox_kvm:
        api_host: '{{ proxmox_api.host }}'
        api_user: '{{ proxmox_api.user }}'
        api_token_id: '{{ proxmox_api.token_id | default(omit) }}'
        api_token_secret: '{{ proxmox_api.token_secret | default(omit) }}'
        node: '{{ vm.node }}'
        newid: '{{ vm.vmid }}'
        clone: '{{ vm.clone }}'
        name: '{{ vm.name }}'
        timeout: '{{ proxmox_timeouts.api }}'
      register: result

    - name: Debug result
      ansible.builtin.debug:
        msg: '{{ result }}'
      when: mode is defined and mode == "debug"

    - name: Update option for VM
      community.general.proxmox_kvm:
        api_host: '{{ proxmox_api.host }}'
        api_user: '{{ proxmox_api.user }}'
        api_token_id: '{{ proxmox_api.token_id | default(omit) }}'
        api_token_secret: '{{ proxmox_api.token_secret | default(omit) }}'
        node: '{{ vm.node }}'
        vmid: '{{ vm.vmid }}'
        cores: '{{ vm.cores }}'
        autostart: '{{ vm.autostart }}'
        memory: '{{ vm.memory }}'
        timeout: '{{ proxmox_timeouts.api }}'
        onboot: '{{ vm.onboot | default(omit)}}'
        ciuser: '{{agent.user}}'
        cipassword: '{{agent.pass}}'
        sskkeys: '{{ agent.sshkeys | default(omit) }}'
        state: present
        update: true
      register: result

    - name: Update IP configuration
      when: vm.ip is defined
      community.general.proxmox_kvm:
        api_host: '{{ proxmox_api.host }}'
        api_user: '{{ proxmox_api.user }}'
        api_token_id: '{{ proxmox_api.token_id | default(omit) }}'
        api_token_secret: '{{ proxmox_api.token_secret | default(omit) }}'
        node: '{{ vm.node }}'
        vmid: '{{ vm.vmid }}'
        ipconfig:
          ipconfig0: 'ip={{ vm.ip }}/{{ cluster_network.cidr }},gw={{ cluster_network.gateway }}'
        state: present
        update: true

    - name: Update disk for vm
      when: vm.disks is defined
      loop: '{{ vm.disks }}'
      vars:
        vmid: '{{ vm.vmid }}'
      loop_control:
        loop_var: disk
      ansible.builtin.include_tasks: disk/disk_change.yaml

    - name: Start VM
      community.general.proxmox_kvm:
        api_host: '{{ proxmox_api.host }}'
        api_user: '{{ proxmox_api.user }}'
        api_token_id: '{{ proxmox_api.token_id }}'
        api_token_secret: '{{ proxmox_api.token_secret }}'
        name: '{{ vm.name | default(omit) }}'
        state: started
        vmid: '{{ vm.vmid | default(omit) }}'

    - name: Wait for server to startup
      ansible.builtin.wait_for:
        port: 22
        host: '{{ vm.ip }}'
        search_regex: OpenSSH
        timeout: '{{ proxmox_timeouts.startup }}'

    - name: Add new host
      ansible.builtin.add_host:
        name: '{{ vm.name }}'
        ansible_host: '{{ vm.ip }}'
        ansible_ssh_user: '{{ agent.user }}'
        # ansible_ssh_pass: '{{ agent.pass }}'
        ansible_become_password: '{{ agent.pass }}'
        become: true
        groups:
          - new_machine
