---
- name: Check Ansible version
  hosts: executor
  gather_facts: false
  become: false
  run_once: true
  tags: always
  tasks:
    - name: Check ansible version
      ansible.builtin.assert:
        that:
          - ansible_version.string is version(ansible_minimal_version, ">=")
          - ansible_version.string is version(ansible_maximal_version, "<")
        msg: 'Ansible must be between {{ ansible_minimal_version }} and {{ ansible_maximal_version }} exclusive - you have {{ ansible_version.string }}'
