---
- name: Common tasks for every playbooks
  import_playbook: common.yaml

- name: List available CT images
  hosts: promox
  vars:
    search:
    nodes: "{{ groups['proxmox'] }}"
  tasks:
    # - name: Debug
    #   ansible.builtin.debug:
    #     msg: '{{ nodes }}'
    # - name: Get available CT images
    #   ansible.builtin.command:
    #     cmd: >-
    #       pvesh get /nodes/{{ ansible_facts.hostname }}/aplinfo --output-format json
    #   changed_when: false
    #   register: aplinfo

    # - name: Display available CT images
    #   ansible.builtin.debug:
    #     msg: '{{ available_ct_images }}'
    #   vars:
    #     search_query: "[?contains(template, '{{ search }}')].template"
    #     available_ct_images: '{{ aplinfo.stdout | from_json | json_query(search_query) }}'

    - name: List vm is running
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: loop_nodes
      vars:
        proxmox_loop_tasks: vm/list_vm.yaml
        proxmox_nodes: '{{ nodes }}'
